[build]
  command = "npm run build"
  publish = "dist"
  functions = "server/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[dev]
  command = "vite"
  targetPort = 5173
  functionsPort = 9999
  functions = "server/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
